// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AddStakeholderInput struct {
	CompanyID string          `json:"companyID"`
	Name      string          `json:"name"`
	Email     string          `json:"email"`
	Role      StakeholderRole `json:"role"`
}

type CapTableEntry struct {
	StakeholderID   *string `json:"stakeholderID,omitempty"`
	StakeholderName string  `json:"stakeholderName"`
	ShareClassName  string  `json:"shareClassName"`
	Shares          Decimal `json:"shares"`
	OwnershipPct    Decimal `json:"ownershipPct"`
}

type CapTableSnapshot struct {
	CompanyID   *string          `json:"companyID,omitempty"`
	TotalShares Decimal          `json:"totalShares"`
	Entries     []*CapTableEntry `json:"entries"`
}

type Company struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	Stakeholders  []*Stakeholder  `json:"stakeholders"`
	ShareClasses  []*ShareClass   `json:"shareClasses"`
	Grants        []*Grant        `json:"grants"`
	FundingRounds []*FundingRound `json:"fundingRounds"`
	SafeNotes     []*SAFENote     `json:"safeNotes"`
	CreatedAt     DateTime        `json:"createdAt"`
}

type CreateCompanyInput struct {
	Name string `json:"name"`
}

type CreateShareClassInput struct {
	CompanyID           string   `json:"companyID"`
	Name                string   `json:"name"`
	IsPreferred         bool     `json:"isPreferred"`
	LiquidationMultiple *Decimal `json:"liquidationMultiple,omitempty"`
	IsParticipating     *bool    `json:"isParticipating,omitempty"`
	ParticipationCap    *Decimal `json:"participationCap,omitempty"`
	PricePerShare       *Decimal `json:"pricePerShare,omitempty"`
	Seniority           *int     `json:"seniority,omitempty"`
	AuthorizedShares    Decimal  `json:"authorizedShares"`
}

type CreateVestingScheduleInput struct {
	CliffMonths         int                  `json:"cliffMonths"`
	TotalMonths         int                  `json:"totalMonths"`
	Frequency           VestingFrequency     `json:"frequency"`
	AccelerationTrigger *AccelerationTrigger `json:"accelerationTrigger,omitempty"`
}

type DilutionModelInput struct {
	CompanyID         string  `json:"companyID"`
	RoundName         string  `json:"roundName"`
	PreMoneyValuation Decimal `json:"preMoneyValuation"`
	AmountRaised      Decimal `json:"amountRaised"`
	NewShareClass     string  `json:"newShareClass"`
	InvestorName      string  `json:"investorName"`
}

type DilutionResult struct {
	PreRound    *CapTableSnapshot `json:"preRound"`
	PostRound   *CapTableSnapshot `json:"postRound"`
	NewInvestor *CapTableEntry    `json:"newInvestor"`
	RoundName   string            `json:"roundName"`
}

type FundingRound struct {
	ID                string   `json:"id"`
	CompanyID         string   `json:"companyID"`
	Name              string   `json:"name"`
	PreMoneyValuation Decimal  `json:"preMoneyValuation"`
	AmountRaised      Decimal  `json:"amountRaised"`
	PricePerShare     Decimal  `json:"pricePerShare"`
	ShareClassID      string   `json:"shareClassID"`
	RoundDate         Date     `json:"roundDate"`
	CreatedAt         DateTime `json:"createdAt"`
}

type Grant struct {
	ID                string           `json:"id"`
	CompanyID         string           `json:"companyID"`
	StakeholderID     string           `json:"stakeholderID"`
	ShareClassID      string           `json:"shareClassID"`
	VestingScheduleID *string          `json:"vestingScheduleID,omitempty"`
	Quantity          Decimal          `json:"quantity"`
	GrantDate         Date             `json:"grantDate"`
	ExercisePrice     Decimal          `json:"exercisePrice"`
	IsExercised       bool             `json:"isExercised"`
	Notes             *string          `json:"notes,omitempty"`
	VestingSchedule   *VestingSchedule `json:"vestingSchedule,omitempty"`
	CreatedAt         DateTime         `json:"createdAt"`
}

type IssueGrantInput struct {
	CompanyID         string   `json:"companyID"`
	StakeholderID     string   `json:"stakeholderID"`
	ShareClassID      string   `json:"shareClassID"`
	VestingScheduleID *string  `json:"vestingScheduleID,omitempty"`
	Quantity          Decimal  `json:"quantity"`
	GrantDate         Date     `json:"grantDate"`
	ExercisePrice     *Decimal `json:"exercisePrice,omitempty"`
	Notes             *string  `json:"notes,omitempty"`
}

type IssueSAFEInput struct {
	CompanyID        string   `json:"companyID"`
	StakeholderID    string   `json:"stakeholderID"`
	InvestmentAmount Decimal  `json:"investmentAmount"`
	ValuationCap     *Decimal `json:"valuationCap,omitempty"`
	DiscountRate     *Decimal `json:"discountRate,omitempty"`
	SafeType         SAFEType `json:"safeType"`
	IssueDate        Date     `json:"issueDate"`
}

type Mutation struct {
}

type Query struct {
}

type RecordFundingRoundInput struct {
	CompanyID         string  `json:"companyID"`
	Name              string  `json:"name"`
	PreMoneyValuation Decimal `json:"preMoneyValuation"`
	AmountRaised      Decimal `json:"amountRaised"`
	PricePerShare     Decimal `json:"pricePerShare"`
	ShareClassID      string  `json:"shareClassID"`
	RoundDate         Date    `json:"roundDate"`
}

type SAFEConversionResult struct {
	SafeID           string  `json:"safeID"`
	SharesIssued     Decimal `json:"sharesIssued"`
	EffectivePps     Decimal `json:"effectivePPS"`
	ConversionMethod string  `json:"conversionMethod"`
}

type SAFENote struct {
	ID               string   `json:"id"`
	CompanyID        string   `json:"companyID"`
	StakeholderID    string   `json:"stakeholderID"`
	InvestmentAmount Decimal  `json:"investmentAmount"`
	ValuationCap     *Decimal `json:"valuationCap,omitempty"`
	DiscountRate     *Decimal `json:"discountRate,omitempty"`
	SafeType         SAFEType `json:"safeType"`
	IsConverted      bool     `json:"isConverted"`
	ConvertedInRound *string  `json:"convertedInRound,omitempty"`
	IssueDate        Date     `json:"issueDate"`
	CreatedAt        DateTime `json:"createdAt"`
}

type ShareClass struct {
	ID                  string   `json:"id"`
	CompanyID           string   `json:"companyID"`
	Name                string   `json:"name"`
	IsPreferred         bool     `json:"isPreferred"`
	LiquidationMultiple Decimal  `json:"liquidationMultiple"`
	IsParticipating     bool     `json:"isParticipating"`
	ParticipationCap    *Decimal `json:"participationCap,omitempty"`
	PricePerShare       *Decimal `json:"pricePerShare,omitempty"`
	Seniority           int      `json:"seniority"`
	AuthorizedShares    Decimal  `json:"authorizedShares"`
	CreatedAt           DateTime `json:"createdAt"`
}

type Stakeholder struct {
	ID        string          `json:"id"`
	CompanyID string          `json:"companyID"`
	Name      string          `json:"name"`
	Email     string          `json:"email"`
	Role      StakeholderRole `json:"role"`
	Grants    []*Grant        `json:"grants"`
	CreatedAt DateTime        `json:"createdAt"`
}

type VestingSchedule struct {
	ID                  string              `json:"id"`
	CliffMonths         int                 `json:"cliffMonths"`
	TotalMonths         int                 `json:"totalMonths"`
	Frequency           VestingFrequency    `json:"frequency"`
	AccelerationTrigger AccelerationTrigger `json:"accelerationTrigger"`
}

type VestingStatus struct {
	GrantID        string  `json:"grantID"`
	AsOfDate       Date    `json:"asOfDate"`
	TotalShares    Decimal `json:"totalShares"`
	VestedShares   Decimal `json:"vestedShares"`
	UnvestedShares Decimal `json:"unvestedShares"`
	PercentVested  Decimal `json:"percentVested"`
	CliffDate      Date    `json:"cliffDate"`
	FullyVestedAt  Date    `json:"fullyVestedAt"`
	IsFullyVested  bool    `json:"isFullyVested"`
}

type WaterfallPayout struct {
	StakeholderID   string  `json:"stakeholderID"`
	StakeholderName string  `json:"stakeholderName"`
	ShareClassName  string  `json:"shareClassName"`
	Shares          Decimal `json:"shares"`
	Payout          Decimal `json:"payout"`
	PayoutPerShare  Decimal `json:"payoutPerShare"`
}

type WaterfallResult struct {
	ExitValuation Decimal            `json:"exitValuation"`
	TotalPayout   Decimal            `json:"totalPayout"`
	Payouts       []*WaterfallPayout `json:"payouts"`
}

type AccelerationTrigger string

const (
	AccelerationTriggerNone          AccelerationTrigger = "NONE"
	AccelerationTriggerSingleTrigger AccelerationTrigger = "SINGLE_TRIGGER"
	AccelerationTriggerDoubleTrigger AccelerationTrigger = "DOUBLE_TRIGGER"
)

var AllAccelerationTrigger = []AccelerationTrigger{
	AccelerationTriggerNone,
	AccelerationTriggerSingleTrigger,
	AccelerationTriggerDoubleTrigger,
}

func (e AccelerationTrigger) IsValid() bool {
	switch e {
	case AccelerationTriggerNone, AccelerationTriggerSingleTrigger, AccelerationTriggerDoubleTrigger:
		return true
	}
	return false
}

func (e AccelerationTrigger) String() string {
	return string(e)
}

func (e *AccelerationTrigger) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccelerationTrigger(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccelerationTrigger", str)
	}
	return nil
}

func (e AccelerationTrigger) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AccelerationTrigger) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AccelerationTrigger) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SAFEType string

const (
	SAFETypePreMoney  SAFEType = "PRE_MONEY"
	SAFETypePostMoney SAFEType = "POST_MONEY"
)

var AllSAFEType = []SAFEType{
	SAFETypePreMoney,
	SAFETypePostMoney,
}

func (e SAFEType) IsValid() bool {
	switch e {
	case SAFETypePreMoney, SAFETypePostMoney:
		return true
	}
	return false
}

func (e SAFEType) String() string {
	return string(e)
}

func (e *SAFEType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SAFEType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SAFEType", str)
	}
	return nil
}

func (e SAFEType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SAFEType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SAFEType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type StakeholderRole string

const (
	StakeholderRoleFounder    StakeholderRole = "FOUNDER"
	StakeholderRoleEmployee   StakeholderRole = "EMPLOYEE"
	StakeholderRoleInvestor   StakeholderRole = "INVESTOR"
	StakeholderRoleAdvisor    StakeholderRole = "ADVISOR"
	StakeholderRoleConsultant StakeholderRole = "CONSULTANT"
)

var AllStakeholderRole = []StakeholderRole{
	StakeholderRoleFounder,
	StakeholderRoleEmployee,
	StakeholderRoleInvestor,
	StakeholderRoleAdvisor,
	StakeholderRoleConsultant,
}

func (e StakeholderRole) IsValid() bool {
	switch e {
	case StakeholderRoleFounder, StakeholderRoleEmployee, StakeholderRoleInvestor, StakeholderRoleAdvisor, StakeholderRoleConsultant:
		return true
	}
	return false
}

func (e StakeholderRole) String() string {
	return string(e)
}

func (e *StakeholderRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = StakeholderRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid StakeholderRole", str)
	}
	return nil
}

func (e StakeholderRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *StakeholderRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e StakeholderRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type VestingFrequency string

const (
	VestingFrequencyMonthly   VestingFrequency = "MONTHLY"
	VestingFrequencyQuarterly VestingFrequency = "QUARTERLY"
	VestingFrequencyAnnually  VestingFrequency = "ANNUALLY"
)

var AllVestingFrequency = []VestingFrequency{
	VestingFrequencyMonthly,
	VestingFrequencyQuarterly,
	VestingFrequencyAnnually,
}

func (e VestingFrequency) IsValid() bool {
	switch e {
	case VestingFrequencyMonthly, VestingFrequencyQuarterly, VestingFrequencyAnnually:
		return true
	}
	return false
}

func (e VestingFrequency) String() string {
	return string(e)
}

func (e *VestingFrequency) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VestingFrequency(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VestingFrequency", str)
	}
	return nil
}

func (e VestingFrequency) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VestingFrequency) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VestingFrequency) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
